package com.shutdowntracker.projectworker.handoff;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(WorkerProjectExportArtifactController.class)
class WorkerProjectExportArtifactControllerTests {

    @Autowired private MockMvc mockMvc;
    @MockBean private WorkerProjectExportArtifactHandoffService handoffService;

    @Test
    void returnsGeneratedCandidateSummary() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID batchId = UUID.randomUUID();
        when(handoffService.generateArtifact(any(ProjectExportArtifactGenerationRequest.class)))
                .thenReturn(new ProjectExportArtifactGenerationResponse(
                        batchId,
                        projectId,
                        "file:///synthetic/export-artifacts/candidate.mspdi.xml",
                        "synthetic-sha256",
                        new ProjectExportArtifactSummary(
                                "candidate.mspdi.xml", "mspdi_xml", 1, 6, 1, 512,
                                "synthetic-sha256",
                                List.of("Candidate schedule derived from accepted source")),
                        "MSPDI/XML candidate schedule generated by project worker from the accepted source. "
                                + "No Microsoft Project write-back was run."
                ));

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody(batchId, projectId, """
                                {
                                  "field": "PERCENT_COMPLETE",
                                  "newValue": "75"
                                }
                                """)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.exportBatchId").value(batchId.toString()))
                .andExpect(jsonPath("$.projectId").value(projectId.toString()))
                .andExpect(jsonPath("$.artifactSummary.artifactFormat").value("mspdi_xml"))
                .andExpect(jsonPath("$.artifactSummary.sourceTaskCount").value(6));

        verify(handoffService).generateArtifact(any(ProjectExportArtifactGenerationRequest.class));
    }

    @Test
    void rejectsMissingAcceptedSourceBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID batchId = UUID.randomUUID();
        String body = requestBody(batchId, projectId, field("PERCENT_COMPLETE", "75"))
                .replace(sourceJson(), "");

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON).content(body))
                .andExpect(status().isBadRequest());
        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsPhysicalPercentBeforeCallingHandoffService() throws Exception {
        assertBadRequest(field("PHYSICAL_PERCENT_COMPLETE", "50"));
    }

    @Test
    void rejectsDuplicateTaskFieldCandidatesBeforeCallingHandoffService() throws Exception {
        assertBadRequest("""
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                },
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                }
                """);
    }

    @Test
    void rejectsUnknownScheduleAuthorityPropertiesBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID batchId = UUID.randomUUID();
        String body = requestBody(batchId, projectId, field("PERCENT_COMPLETE", "75"))
                .replace("\"leafTask\": true,", "\"leafTask\": true,\n                        \"plannedStart\": \"2026-01-05T07:00:00Z\",");
        performBadRequest(body);
    }

    @Test
    void rejectsNumericEnumAliasesBeforeCallingHandoffService() throws Exception {
        assertBadRequest("""
                {
                  "field": 0,
                  "newValue": "75"
                }
                """);
    }

    @Test
    void rejectsDuplicateJsonPropertiesBeforeCallingHandoffService() throws Exception {
        assertBadRequest("""
                {
                  "field": "PERCENT_COMPLETE",
                  "field": "ACTUAL_START",
                  "newValue": "75"
                }
                """);
    }

    @Test
    void rejectsSummaryMissingAndNonCanonicalTaskIdentityBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID batchId = UUID.randomUUID();
        String valid = requestBody(batchId, projectId, field("PERCENT_COMPLETE", "75"));
        for (String body : List.of(
                valid.replace("\"leafTask\": true", "\"leafTask\": false"),
                valid.replace("\"microsoftProjectTaskUid\": \"2\",", ""),
                valid.replace("\"microsoftProjectTaskUid\": \"2\"", "\"microsoftProjectTaskUid\": \"02\""),
                valid.replace("\"microsoftProjectTaskId\": \"2\"", "\"microsoftProjectTaskId\": \"+2\"")
        )) {
            performBadRequest(body);
        }
    }

    @Test
    void rejectsNonzeroFractionalActualBeforeCallingHandoffService() throws Exception {
        assertBadRequest(field("ACTUAL_START", "2026-01-05T16:00:00.001+08:00"));
    }

    private void assertBadRequest(String fieldValues) throws Exception {
        performBadRequest(requestBody(UUID.randomUUID(), UUID.randomUUID(), fieldValues));
    }

    private void performBadRequest(String body) throws Exception {
        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON).content(body))
                .andExpect(status().isBadRequest());
        verifyNoInteractions(handoffService);
    }

    private String field(String field, String value) {
        return "{\n  \"field\": \"" + field + "\",\n  \"newValue\": \"" + value + "\"\n}";
    }

    private String sourceJson() {
        return """
                    "source": {
                      "sourceFileId": "00000000-0000-0000-0000-0000000000f1",
                      "storageUri": "file:///synthetic/accepted-source.mspdi.xml",
                      "contentHash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                    },
                """;
    }

    private String requestBody(UUID batchId, UUID projectId, String fieldValues) {
        return """
                {
                  "exportBatchId": "%s",
                  "projectId": "%s",
                  "outputPath": ".shutdown-tracker/export-artifacts/%s.mspdi.xml",
                  "artifactRequest": {
                    "projectName": "Synthetic Export Preview",
                %s    "tasks": [
                      {
                        "importedTaskId": "synthetic-task-a1",
                        "microsoftProjectTaskUid": "2",
                        "microsoftProjectTaskId": "2",
                        "taskName": "Synthetic Task A1",
                        "leafTask": true,
                        "fieldValues": [
                          %s
                        ]
                      }
                    ]
                  }
                }
                """.formatted(batchId, projectId, batchId, sourceJson(), fieldValues);
    }
}
