package com.shutdowntracker.projectworker.handoff;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import com.shutdowntracker.projectworker.exporter.ProjectExportArtifactService;
import java.net.URI;
import java.nio.file.Path;
import java.util.Objects;
import org.springframework.stereotype.Service;

@Service
public class WorkerProjectExportArtifactHandoffService {

    private static final String LOCAL_FILE_SCHEME = "file";
    private static final String MESSAGE =
            "MSPDI/XML candidate schedule generated by project worker from the accepted source. "
                    + "No Microsoft Project write-back was run.";

    private final ProjectExportArtifactService exportArtifactService;

    public WorkerProjectExportArtifactHandoffService(ProjectExportArtifactService exportArtifactService) {
        this.exportArtifactService = exportArtifactService;
    }

    public ProjectExportArtifactGenerationResponse generateArtifact(ProjectExportArtifactGenerationRequest request) {
        Objects.requireNonNull(request, "request is required.");
        Path outputPath = Path.of(request.outputPath()).toAbsolutePath().normalize();
        Path sourcePath = resolveLocalPath(request.artifactRequest().source().storageUri());
        ProjectExportArtifactSummary summary =
                exportArtifactService.generate(request.artifactRequest(), sourcePath, outputPath);

        return new ProjectExportArtifactGenerationResponse(
                request.exportBatchId(),
                request.projectId(),
                outputPath.toUri().toString(),
                summary.sha256(),
                summary,
                MESSAGE
        );
    }

    private Path resolveLocalPath(String storageUri) {
        URI uri = URI.create(storageUri);
        if (uri.getScheme() == null) {
            return Path.of(storageUri).toAbsolutePath().normalize();
        }
        if (LOCAL_FILE_SCHEME.equalsIgnoreCase(uri.getScheme())) {
            return Path.of(uri).toAbsolutePath().normalize();
        }
        throw new IllegalArgumentException(
                "Candidate schedule generation currently requires a local file source URI."
        );
    }
}
